#!/bin/bash
#|||||||||||||#
#|by_51M30N|||#
#|for__StuART|#
#|||||||||||||# rev 01092019
#|||||||||||||#


######################################################
#                                                    #
#  OSC_to_GPIO "input_port"                           #
#                                                    #
######################################################

#init des variables
chemin="StuART/OSC/"
fichier="OSC_to_GPIO.pd"

#test de l'argument port
    if [ $1 ]
    then
        port=$1
    else
        echo "input_port :"
        read
        port=$REPLY
    fi

#ecriture du patch puredata
	echo "#N canvas 271 164 434 73 10;" > temp.pd
	echo "#X obj 219 32 OSC_to_GPIO ;" >> temp.pd

#Copie et ouverture du fichier généré
	chemin=$chemin"temp_"$fichier
	cp temp.pd $chemin
	rm temp.pd
	echo "OPEN : "$chemin
	pd -open $chemin &

exit
